### ISSUE TITLE
No sdist tarball with source on pypi, or release on Github

### ISSUE THREAD

**Issue by goanpeca** [etasnadi/napari_nucleaizer#1]
We are in the process of creating conda packages for [napari plugins](https://www.napari-hub.org/) and related dependencies.

See https://github.com/conda-forge/staged-recipes/pull/18050

Once this recipe passes all the checks, every time a new release goes into PyPI, a PR will be created automatically, with usually very minor need for changes so the process of maintaining this moving forward is small. Also the @conda-forge/napari team will be available to help as needed.

You can read a bit more about conda-forge at https://conda-forge.org/#contribute

---

To be able to make this work we rely on:
- The sources tarball when uploaded to pypi (currently only [wheels](https://pypi.org/project/napari-nucleaizer/#files) are available). 
- Or a github release. There is a tag for the latest version but not an actual [release].(https://github.com/etasnadi/napari_nucleaizer/releases)

Do you think you could enable either of these options @etasnadi?

Thanks!

**Comment by etasnadi** [comment]
Hi,

I upladed the sdist to PyPI.

Ervin

**Comment by goanpeca** [comment]
Hi @etasnadi, thanks!
