### ISSUE TITLE
Unable to install napari plugin

### ISSUE THREAD

**Issue by N0AHt** [etasnadi/napari_nucleaizer#3]
when trying to install the plugin via napari (or via CLI) it fails due to dependence on tensorflow-gpu

**Comment by etasnadi** [comment]
Hi,

How did you install it through the CLI exactly? Can you please show the command, your python version and operating system, and the error you got?

Thanks

**Comment by etasnadi** [comment]
The reporter did not describe the details of the issue so I am closing it.
